### ISSUE TITLE
This all of a sudden stopped working for me

### ISSUE THREAD

**Issue by thc1967** [elonmallin/vscode-phpunit#12]
I've grown quite fond of using Ctrl + Alt + T to immediately run the test function I'm working on or the whole file, right within my development environment. I can tell you that my "T" key was wearing down from all the use it was getting.

This worked great all the way through yesterday evening - September 10.

This morning, Ctrl+Alt+T opens the command drop-down list and asks me to run my test class. If I hit Enter or click it, nothing happens.

![commandribbon](https://user-images.githubusercontent.com/2651772/30283431-18bc4340-96e6-11e7-9cda-305b5ae2f7ea.png)

This is the same behavior as if I hit Ctrl+Shift+P, then go to PHPUnit Test. It simply won't run tests within the editor any more. :(

I've tried reinstalling the package and restarting VSCode to no avail.

Any advice would be appreciated! Thanks!

**Comment by elonmallin** [comment]
Hi, thanks for reporting this. The problem is actually that the output channel isn't shown by default when a test is run.

Make sure you select phpunit as the output channel.
![image](https://user-images.githubusercontent.com/9149793/30284645-cb0447de-971b-11e7-8180-dc86273217d1.png)

It should show by default though. I will do a fix for this and publish to the marketplace!

Regarding why you get the quick pick window instead of running the whole class is how I updated it to be.
[Changelog](https://github.com/elonmallin/vscode-phpunit/blob/master/CHANGELOG.md)
You have to have the cursor directly on a function or class to instantly run it. Otherwise the quick pick window is shown. Would you rather never have the quick pick window and just run the whole class? Please try it out this way I think it is better. Otherwise I would consider a configuration flag to allow it to work like before.

**Comment by thc1967** [comment]
Thanks for the quick response! 

With phpunit selected as the output channel, I can see that it really does test. I just wasn't seeing it before because the output channel got changed somehow.

However, even with the cursor on a function name (or the entire function name selected) and phpunit selected as the output channel, it will only run the full-class test. It will never run the single-function test (or I can't figure out how to make it).

I really liked the way it behaved before. It was perfectly predictable and took only a quick single key combination to run exactly the test I wanted. No extra steps or keystrokes.

I'm good with learning behavior and patterns to make an editor do what I want with fewer keystrokes and less thinking and looking. I think most developers are.

Thanks again for a great add-on! (It was actually one of the very large drivers in my decision to switch from Atom to VSCode.)

**Comment by elonmallin** [comment]
I pushed an update to show the output channel on test run. I noticed though that there is some bug in there. It doesn't always happen but sometimes the function or class runs instantly if the cursor is on it and sometimes not. Will have to fix it and spam ppl to update again =(

I guess I should add a config setting to make it never show the quick pick window just like before.

Thanks, that is really cool to hear!

**Comment by thc1967** [comment]
Yes, please! The option to make it work like previous would be awesome! Thanks!

Don't sweat the update spam. I think most people run enough add-ons that we are prompted to update several times each week anyway. I know I am! :)

**Comment by elonmallin** [comment]
Pushed another update. There is now a flag to run the whole class test instead of showing the quick pick window like before `preferRunClassTestOverQuickPickWindow (default: false)`. Change this to `true` and it will work like before.

**Comment by thc1967** [comment]
The option for running the class works great, thanks!

But it still doesn't auto-run only the function for me if I have a cursor in its name. :(

Is there something I can do to help debug why?

**Comment by elonmallin** [comment]
Hmm, ok. I'm on windows 10 and it's working for me. Are you on a mac? I put the cursor in the function name just like before:
`public function testSomethingToTry()` cursor somewhere on the function name.

What is happening for you? Is it running the whole class then? Could you paste the code snippet or function that you are testing and I can see if there's something with that.

For you to manually debug you'd need to clone the repo and do an `npm install`. Then it should be debuggable I think.

Thanks for your help, sorry for the trouble.

**Comment by thc1967** [comment]
I'm on Windows 10. VSCode 64-bit.

Reproduction steps:

1) Create any type of test case, basic simplistic or otherwise. Let's call it this:

```PHP
<?php

namespace Tests\Unit;

use Tests\TestCase;

class BasicTest extends TestCase
{
    /** @test */
    public function basic_test_one()
    {
        $this->assertTrue(true);
    }

    /** @test */
    public function basic_test_two()
    {
        $this->assertTrue(false);
    }
}
```

2) Set the cursor in the name of either test function.

3) Invoke the hot key I've assigned to run test (Ctrl+Alt+T).

4) Result (truncated):

```
...
FAILURES!
Tests: 2, Assertions: 2, Failures: 1.
```

Notice that it ran two tests, so it ran the whole class, not just the one function I had the cursor inside of.

Same result if I invoke the command from the command menu.

And it's no trouble. I can work around it by running a single function test from a command line. Inside the editor just makes it more convenient, which is why I love this add-on. Just need to figure out why you and I are getting different behavior on the same platform.

**Comment by elonmallin** [comment]
Ah I see. I thought functions had to start with `test*`. There was a PR that expects function names starting with that. Will have to make it not rely on that. Thanks.

**Comment by thc1967** [comment]
Confirmed. Works as expected when "test" is the first 4 characters of the function name.

Must have been a recent PR? Because it worked up until this morning... :(

**Comment by elonmallin** [comment]
It should work now. Could you install the [phpunit-2.1.1.vsix](https://github.com/elonmallin/vscode-phpunit/releases/download/v2.1.1/phpunit-2.1.1.vsix) manually and check?

![install-vsix](https://user-images.githubusercontent.com/9149793/30294220-9ecbe304-973c-11e7-9802-2c399ce21a10.png)

Don't want to spam even more. Thanks a lot!

**Comment by thc1967** [comment]
Awesome! That worked!

And sorry for the delay. Long drive home.

**Comment by elonmallin** [comment]
No problem. Pushed the new version to the marketplace, thanks for your help.
